### ISSUE TITLE
Collect Security Alert Data

### ISSUE THREAD

**Issue by perploug** [zalando-incubator/roadblock#22]
## Expected Behavior
Roadblock should collect security alerts and place in a table

## Actual Behavior
Does not currently collect this data

## Tasks
- [x] Create database schema
- [x] Setup task to run as an org task
- [x] Query Github with its V4 api to get this data
- [x] Map data to new database schema
